/**:
  ros__parameters:
    wheel_radius: 0.2286
    wheel_width: 0.2159
    wheel_base: 1.64
    wheel_tread: 0.98
    front_overhang: 0.25
    rear_overhang: 0.40
    left_overhang: 0.10786
    right_overhang: 0.10786
    vehicle_height: 1.85
    max_steer_angle: 0.78539