base_link:
  sensor_kit_base_link: # lidar
    x: 0.25
    y: 0.0
    z: 2.2
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 1.30
    y: 0.0
    z: 0.6786
    roll: 0.0
    pitch: 0.49916
    yaw: 0.0
